import dotenv
import os

dotenv.load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_REGION = os.getenv("PINECONE_REGION")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME")
MONGODB_URL = os.getenv("MONGODB_URL")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

if not OPENAI_API_KEY or not PINECONE_API_KEY or not PINECONE_REGION or not PINECONE_INDEX_NAME or not MONGODB_URL:
    raise ValueError("OPENAI_API_KEY or PINECONE_API_KEY or PINECONE_REGION or PINECONE_INDEX_NAME or MONGODB_URL is not set")
